version: '3.8'

services:
  shopware-6.5:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SHOPWARE_VERSION: 6.5
        PHP_VERSION: 8.1
    container_name: shopware-dev-6.5
    ports:
      - "8065:80"
      - "3365:3306"
      - "6375:6379"
    volumes:
      - "./src:/var/www/html/custom/plugins/development"
    environment:
      - XDEBUG_ENABLED=1
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
      - SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS=1
      - DISABLE_ADMIN_COMPILATION_TYPECHECK=1
    networks:
      - shopware-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/admin"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 2m

  shopware-6.6:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SHOPWARE_VERSION: 6.6
        PHP_VERSION: 8.2
    container_name: shopware-dev-6.6
    ports:
      - "8066:80"
      - "3366:3306"
      - "6376:6379"
    volumes:
      - "./src:/var/www/html/custom/plugins/development"
    environment:
      - XDEBUG_ENABLED=1
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
      - SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS=1
      - DISABLE_ADMIN_COMPILATION_TYPECHECK=1
    networks:
      - shopware-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/admin"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 2m

  shopware-6.7:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SHOPWARE_VERSION: 6.7
        PHP_VERSION: 8.3
    container_name: shopware-dev-6.7
    ports:
      - "8067:80"
      - "3367:3306"
      - "6377:6379"
    volumes:
      - "./src:/var/www/html/custom/plugins/development"
    environment:
      - XDEBUG_ENABLED=1
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
      - SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS=1
      - DISABLE_ADMIN_COMPILATION_TYPECHECK=1
    networks:
      - shopware-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/admin"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 2m

networks:
  shopware-dev:
    driver: bridge
    external: false

volumes:
  mysql-6.5:
  mysql-6.6:
  mysql-6.7:
