name: Build and Push Shopware Dev Images

on:
  push:
    branches:
      - main
    tags:
      - 'v6.5.*'
      - 'v6.6.*'
      - 'v6.7.*'
  schedule:
    # Nightly rebuild to get latest patch versions
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/shopware-dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        shopware_version: ["6.5", "6.6", "6.7"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.shopware_version }}
            type=raw,value=${{ matrix.shopware_version }}-{{date 'YYYYMMDD'}}
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SHOPWARE_VERSION=${{ matrix.shopware_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run smoke tests
        run: |
          chmod +x .github/scripts/smoke-test.sh
          .github/scripts/smoke-test.sh ${{ matrix.shopware_version }}